version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: budget-mongo-dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data-dev:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-data-dev: